set -l kittens\
  @\
  update-self\
  edit-in-kitty\
  clipboard\
  icat\
  ssh\
  transfer panel\
  quick-access-terminal\
  unicode-input\
  show-key\
  desktop-ui\
  mouse-demo\
  hyperlinked-grep\
  ask\
  hints\
  diff\
  notify\
  themes\
  run-shell\
  choose-fonts\
  choose-files\
  query-terminal\
;

complete -f kitten

complete -f kitten -s h -l help -d "Show help for this command"

#main command parameters
complete -f kitten -l version -n "not __fish_seen_subcommand_from $kittens" -d "The current kitten version."
#main command
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a @                     -d "Control kitty remotely"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a update-self           -d "Update this kitten binary"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a edit-in-kitty         -d "Edit a file in a kitty overlay window"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a clipboard             -d "Copy/paste with the system clipboard, even over SSH"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a icat                  -d "Display images in the terminal"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a ssh                   -d "Truly convenient SSH"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a transfer              -d "Transfer files easily over the TTY device"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a panel                 -d "Use a command line program to draw a GPU accelerated panel on your desktop"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a quick-access-terminal -d "A quick access terminal window that you can bring up instantly with a keypress or a command."
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a unicode-input         -d "Browse and select unicode characters by name"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a show-key              -d "Show the codes generated by the terminal for key presses in various keyboard modes"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a desktop-ui            -d "Implement various desktop components for use with lightweight compositors/window managers on Linux"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a mouse-demo            -d "Demo the mouse handling kitty implements for terminal programs"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a hyperlinked-grep      -d "Add hyperlinks to the output of ripgrep"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a ask                   -d "Ask the user for input"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a hints                 -d "Select text from screen with keyboard"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a diff                  -d "Pretty, side-by-side diffing of files and images"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a notify                -d "Send notifications to the user"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a themes                -d "Manage kitty color schemes easily"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a run-shell             -d "Run the user's shell with shell integration enabled"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a choose-fonts          -d "Choose the fonts used in kitty"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a choose-files          -d "Choose files, fast"
complete -f kitten -n "not __fish_seen_subcommand_from $kittens" -a query-terminal        -d "Query the terminal for various capabilities"

#@(remote control) parameters
complete -f kitten -n "__fish_seen_subcommand_from @" -l to                            -d "Address for the kitty instance to control"
complete -f kitten -n "__fish_seen_subcommand_from @" -l password                      -d "Password to use when contacting kitty"
complete -f kitten -n "__fish_seen_subcommand_from @" -l password-file                 -d "File from which to read the password"
complete -f kitten -n "__fish_seen_subcommand_from @" -l password-env                  -d "The name of an environment variable to read the password from"
complete -f kitten -n "__fish_seen_subcommand_from @" -l use-password -a if-available  -d "use password if provided"
complete -f kitten -n "__fish_seen_subcommand_from @" -l use-password -a always        -d "always use password"
complete -f kitten -n "__fish_seen_subcommand_from @" -l use-password -a never         -d "do not use password"
complete -f kitten -n "__fish_seen_subcommand_from @" -l use-password                  -d "Control when to use the supplied password"
#@(remote control) commands
complete -f kitten -n "__fish_seen_subcommand_from @" -a action                 -d "Run the specified mappable action"
complete -f kitten -n "__fish_seen_subcommand_from @" -a close-tab              -d "Close the specified tabs"
complete -f kitten -n "__fish_seen_subcommand_from @" -a close-window           -d "Close the specified windows"
complete -f kitten -n "__fish_seen_subcommand_from @" -a create-marker          -d "Create a marker that highlights specified text"
complete -f kitten -n "__fish_seen_subcommand_from @" -a detach-tab             -d "Detach the specified tabs and place them in a different/new OS window"
complete -f kitten -n "__fish_seen_subcommand_from @" -a detach-window          -d "Detach the specified windows and place them in a different/new tab"
complete -f kitten -n "__fish_seen_subcommand_from @" -a disable-ligatures      -d "Control ligature rendering"
complete -f kitten -n "__fish_seen_subcommand_from @" -a env                    -d "Change environment variables seen by future children"
complete -f kitten -n "__fish_seen_subcommand_from @" -a focus-tab              -d "Focus the specified tab"
complete -f kitten -n "__fish_seen_subcommand_from @" -a focus-window           -d "Focus the specified window"
complete -f kitten -n "__fish_seen_subcommand_from @" -a get-colors             -d "Get terminal colors"
complete -f kitten -n "__fish_seen_subcommand_from @" -a get-text               -d "Get text from the specified window"
complete -f kitten -n "__fish_seen_subcommand_from @" -a goto-layout            -d "Set the window layout"
complete -f kitten -n "__fish_seen_subcommand_from @" -a kitten                 -d "Run a kitten"
complete -f kitten -n "__fish_seen_subcommand_from @" -a last-used-layout       -d "Switch to the last used layout"
complete -f kitten -n "__fish_seen_subcommand_from @" -a launch                 -d "Run an arbitrary process in a new window/tab"
complete -f kitten -n "__fish_seen_subcommand_from @" -a load-config            -d "(Re)load a config file"
complete -f kitten -n "__fish_seen_subcommand_from @" -a ls                     -d "List tabs/windows"
complete -f kitten -n "__fish_seen_subcommand_from @" -a new-window             -d "Open new window"
complete -f kitten -n "__fish_seen_subcommand_from @" -a remove-marker          -d "Remove the currently set marker, if any."
complete -f kitten -n "__fish_seen_subcommand_from @" -a resize-os-window       -d "Resize/show/hide/etc. the specified OS Windows"
complete -f kitten -n "__fish_seen_subcommand_from @" -a resize-window          -d "Resize the specified windows"
complete -f kitten -n "__fish_seen_subcommand_from @" -a run                    -d "Run a program on the computer in which kitty is running and get the output"
complete -f kitten -n "__fish_seen_subcommand_from @" -a scroll-window          -d "Scroll the specified windows"
complete -f kitten -n "__fish_seen_subcommand_from @" -a select-window          -d "Visually select a window in the specified tab"
complete -f kitten -n "__fish_seen_subcommand_from @" -a send-key               -d "Send arbitrary key presses to the specified windows"
complete -f kitten -n "__fish_seen_subcommand_from @" -a send-text              -d "Send arbitrary text to specified windows"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-background-image   -d "Set the background image"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-background-opacity -d "Set the background opacity"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-colors             -d "Set terminal colors"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-enabled-layouts    -d "Set the enabled layouts in tabs"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-font-size          -d "Set the font size in the active top-level OS window"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-spacing            -d "Set window paddings and margins"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-tab-color          -d "Change the color of the specified tabs in the tab bar"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-tab-title          -d "Set the tab title"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-user-vars          -d "Set user variables on a window"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-window-logo        -d "Set the window logo"
complete -f kitten -n "__fish_seen_subcommand_from @" -a set-window-title       -d "Set the window title"
complete -f kitten -n "__fish_seen_subcommand_from @" -a signal-child           -d "Send a signal to the foreground process in the specified windows"

#update-self
complete -x kitten -n "__fish_seen_subcommand_from update-self" -l fetch-version  -d "The version to fetch"

#edit-in-kitty
complete -F kitten -n "__fish_seen_subcommand_from edit-in-kitty"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l tab-title       -d "The title for the new tab if launching in a new tab"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l cwd             -d "The working directory for the newly launched child"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l env             -d "Environment variables to set in the child process "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l var             -d "User variables to set in the created window "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l next-to         -d "A match expression to select the window next to which the new window is created "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-class -d "Set the WM_CLASS property on X11 and the application id property on Wayland "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-name  -d "Set the WM_NAME property on X11 for the newly created OS Window when using--type"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-title -d "Set the title for the newly created OS window "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l logo            -d "Path to a PNG image to use as the logo for the newly created window "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l logo-position   -d "The position for the window logo. "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l logo-alpha      -d "The amount the window logo should be faded into the background"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l color           -d "Change colors in the newly launched window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l spacing         -d "Set the margin and padding for the newly created window "
complete -f kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l hold            -d "Keep the window open even after the command being executed exits"
complete -f kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l hold-after-ssh  -d "Run a local shell after disconnecting from the remote host"
complete -f kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l max-file-size   -d "The maximum allowed size of files to edit "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l title \
                                                                  -l window-title    -d "The title to set for the new window"
complete -f kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l dont-take-focus \
                                                                  -l keep-focus      -d "Keep the focus on the currently active window instead of switching to the newly opened window "

complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a window       -d "A new kitty window in the current tab"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a tab          -d "A new tab in the current OS window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a os-window    -d "A new operating system window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a overlay      -d "An overlay window covering the current active kitty window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a overlay-main -d "An overlay window covering the current active kitty window but in the main "
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a background   -d "The process will be run in the background without a kitty window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a clipboard    -d "The process's output will be copied to the system clipboard"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a primary      -d "The process's output will be copied to the primary selection"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type -a os-panel     -d "A new operating system window as pane"
complete -f kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l type                 -d "Where to launch the child process"

complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a default  -d "layout dependent placement"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a after    -d "place the new window after the active window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a before   -d "place the new window before the active window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a first    -d "place the new window at the beginning of the tab"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a hsplit   -d "place the new window in a horizontal split with the active window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a last     -d "place the new window at the end of the tab"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a neighbor -d "same behavior as after"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a split    -d "place the new window in an automatic split with the active window"
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location -a vsplit   -d "place the new window in a vertical split with the active window"
complete -f kitten -n "__fish_seen_subcommand_from edit-in-kitty"  -l location             -d "Where to place the newly created window when it is added to a tab which already has existing windows in it"

complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-state -a normal      
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-state -a fullscreen  
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-state -a maximized   
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-state -a minimized   
complete -x kitten -n "__fish_seen_subcommand_from edit-in-kitty" -l os-window-state -d "The initial state for the newly created OS Window."

#clipboard
complete -F kitten -n "__fish_seen_subcommand_from clipboard"
complete -f kitten -n "__fish_seen_subcommand_from clipboard" -s g -l get-clipboard       -d "Output the current contents of the clipboard to STDOUT"
complete -f kitten -n "__fish_seen_subcommand_from clipboard" -s p -l use-primary         -d "Use the primary selection rather than the clipboard"
complete -f kitten -n "__fish_seen_subcommand_from clipboard" -s m -l mime                -d "The mimetype of the specified file"
complete -f kitten -n "__fish_seen_subcommand_from clipboard" -s a -l alias               -d "Specify aliases for MIME types"
complete -f kitten -n "__fish_seen_subcommand_from clipboard"      -l wait-for-completion -d "Wait till the copy to clipboard is complete before exiting"
complete -f kitten -n "__fish_seen_subcommand_from clipboard"      -l password            -d "password to use when accessing the clipboard"
complete -f kitten -n "__fish_seen_subcommand_from clipboard"      -l human-name          -d "human friendly name to show the user when asking for permission to access the clipboard"

#Usage: kitten icat [options] image-file-or-url-or-directory ...
#
#A cat like utility to display images in the terminal. You can specify multiple
#image files and/or directories. Directories are scanned recursively for image
#files. If STDIN is not a terminal, image data will be read from it as well. You
#can also specify HTTP(S) or FTP URLs which will be automatically downloaded and
#displayed.
#
#Options:
#  --align [=center]
#    Horizontal alignment for the displayed image.
#    Choices: center, left, right
#
#  --place
#    Choose where on the screen to display the image. The image will be scaled to
#    fit into the specified rectangle. The syntax for specifying rectangles is
#    <width>x<height>@<left>x<top>. All measurements are in cells (i.e. cursor
#    positions) with the origin (0, 0) at the top-left corner of the screen. Note
#    that the --align option will horizontally align the image within this
#    rectangle. By default, the image is horizontally centered within the
#    rectangle. Using place will cause the cursor to be positioned at the top
#    left corner of the image, instead of on the line after the image.
#
#  --scale-up [=no]
#    Cause images that are smaller than the specified area to be scaled up to use
#    as much of the specified area as possible. The specified area depends on
#    either the --place or the --fit options.
#
#  --fit [=width]
#    When not using --place, control how the image is scaled relative to the
#    screen. You can have it fit in the screen width or height or both or
#    neither.
#    Choices: width, both, height, none
#
#  --background [=none]
#    Specify a background color, this will cause transparent images to be
#    composited on top of the specified color.
#
#  --mirror [=none]
#    Mirror the image about a horizontal or vertical axis or both.
#    Choices: none, both, horizontal, vertical
#
#  --clear [=no]
#    Remove all images currently displayed on the screen. Note that this cannot
#    work with terminal multiplexers such as tmux since only the multiplexer can
#    know the position of the screen.
#
#  --clear-all [=no]
#    Remove all images from screen and scrollback. Note that with terminal
#    multiplexers like tmux, this will move images from all panes.
#
#  --transfer-mode [=detect]
#    Which mechanism to use to transfer images to the terminal. The default is to
#    auto-detect. file means to use a temporary file, memory means to use shared
#    memory, stream means to send the data via terminal escape codes. Note that
#    if you use the file or memory transfer modes and you are connecting over a
#    remote session then image display will not work.
#    Choices: detect, file, memory, stream
#
#  --detect-support [=no]
#    Detect support for image display in the terminal. If not supported, will
#    exit with exit code 1, otherwise will exit with code 0 and print the
#    supported transfer mode to stderr, which can be used with the
#    --transfer-mode option.
#
#  --detection-timeout [=10]
#    The amount of time (in seconds) to wait for a response from the terminal,
#    when detecting image display support.
#
#  --use-window-size
#    Instead of querying the terminal for the window size, use the specified
#    size, which must be of the format:
#    width_in_cells,height_in_cells,width_in_pixels,height_in_pixels
#
#  --print-window-size [=no]
#    Print out the window size as <width>x<height> (in pixels) and quit. This is
#    a convenience method to query the window size if using kitten icat from a
#    scripting language that cannot make termios calls.
#
#  --stdin [=detect]
#    Read image data from STDIN. The default is to do it automatically, when
#    STDIN is not a terminal, but you can turn it off or on explicitly, if
#    needed.
#    Choices: detect, no, yes
#
#  --silent [=no]
#    Not used, present for legacy compatibility.
#
#  --engine [=auto]
#    The engine used for decoding and processing of images. The default is to use
#    the most appropriate engine.  The builtin engine uses Go's native imaging
#    libraries. The magick engine uses ImageMagick which requires it to be
#    installed on the system.
#    Choices: auto, builtin, magick
#
#  --z-index, -z [=0]
#    Z-index of the image. When negative, text will be displayed on top of the
#    image. Use a double minus for values under the threshold for drawing images
#    under cell background colors. For example, --1 evaluates as -1,073,741,825.
#
#  --loop, -l [=-1]
#    Number of times to loop animations. Negative values loop forever. Zero means
#    only the first frame of the animation is displayed. Otherwise, the animation
#    is looped the specified number of times.
#
#  --hold [=no]
#    Wait for a key press before exiting after displaying the images.
#
#  --unicode-placeholder [=no]
#    Use the Unicode placeholder method to display the images. Useful to display
#    images from within full screen terminal programs that do not understand the
#    kitty graphics protocol such as multiplexers or editors. See
#    graphics_unicode_placeholders for details. Note that when using this method,
#    images placed (with --place) that do not fit on the screen, will get wrapped
#    at the screen edge instead of getting truncated. This wrapping is per line
#    and therefore the image will look like it is interleaved with blank lines.
#
#  --passthrough [=detect]
#    Whether to surround graphics commands with escape sequences that allow them
#    to passthrough programs like tmux. The default is to detect when running
#    inside tmux and automatically use the tmux passthrough escape codes. Note
#    that when this option is enabled it implies --unicode-placeholder as well.
#    Choices: detect, none, tmux
#
#  --image-id [=0]
#    The graphics protocol id to use for the created image. Normally, a random id
#    is created if needed. This option allows control of the id. When multiple
#    images are sent, sequential ids starting from the specified id are used.
#    Valid ids are from 1 to 4294967295. Numbers outside this range are
#    automatically wrapped.
#
#  --no-trailing-newline, -n [=no]
#    By default, the cursor is moved to the next line after displaying an image.
#    This option, prevents that. Should not be used when catting multiple images.
#    Also has no effect when the --place option is used.
#
#  --help, -h [=no]
#    Show help for this command
#
#kitten icat 0.45.0 created by Kovid Goyal
#