
complete -F bindfs
complete -f bindfs -s o                                                                                -d "Mount options"
complete -f bindfs -s r                                                                                -d "Mount strictly read-only"
complete -f bindfs -s d                                                                                -d "Enable debug output (implies -f)"
complete -f bindfs -s f                                                                                -d "Foreground operation"
complete -f bindfs -s h -l help                                                                        -d "Print help and exit"
complete -f bindfs -s V -l version                                                                     -d "Print version number and exit"
complete -x bindfs -s p -l perms                                                                       -d "Specify permissions, similar to chmod"
complete -x bindfs -s u -l force-user                                       -a "__fish_complete_users" -d "Set file owner"
complete -x bindfs -s g -l force-group                                     -a "__fish_complete_groups" -d "Set file group"
complete -x bindfs -s m -l mirror                                           -a "__fish_complete_users" -d "Comma-separated list of users who will see themselves as the owners of all files"
complete -x bindfs -s M -l mirror-only                                      -a "__fish_complete_users" -d "Like --mirror but disallow access for all other users"
complete -x bindfs      -l create-for-user                                  -a "__fish_complete_users" -d "New files owned by specified user "
complete -x bindfs      -l create-for-group                                -a "__fish_complete_groups" -d "New files owned by specified group "
complete -x bindfs      -l resolved-symlink-deletion -a "deny symlink-only symlink-first target-first" -d "Decide how to delete resolved symlinks"
complete -x bindfs      -l map                                                                         -d "Let user2 see files of user1 as his own"
complete -x bindfs      -l map-passwd                                                                  -d "Load uid mapping from passwd-like file"
complete -x bindfs      -l map-group                                                                   -d "Load gid mapping from group-like file"
complete -x bindfs      -l map-passwd-rev                                                              -d "Load reversed uid mapping from passwd-like file"
complete -x bindfs      -l map-group-rev                                                               -d "Load reversed gid mapping from group-like file"
complete -x bindfs      -l uid-offset                                                                  -d "Set file uid = uid + offset"
complete -x bindfs      -l gid-offset                                                                  -d "Set file gid = gid + offset"
complete -x bindfs      -l create-with-perms                                                           -d "Alter permissions of new files"
complete -x bindfs      -l chmod-filter                                                                -d "Change permissions of chmod requests"
complete -x bindfs      -l read-rate                                                                   -d "Limit to bytes/sec that can be read"
complete -x bindfs      -l write-rate                                                                  -d "Limit to bytes/sec that can be written"
complete -x bindfs      -l forward-odirect                                                             -d "Forward O_DIRECT (it's cleared by default)"
complete -f bindfs      -l fuse-version                                                                -d "Print version of FUSE library"
complete -f bindfs      -l create-as-user                                                              -d "New files owned by creator (default for root) "
complete -f bindfs      -l create-as-mounter                                                           -d "New files owned by fs mounter (default for users)"
complete -f bindfs      -l chown-normal                                                                -d "Try to chown the original files"
complete -f bindfs      -l chgrp-normal                                                                -d "Try to chgrp the original files"
complete -f bindfs      -l chmod-normal                                                                -d "Try to chmod the original files"
complete -f bindfs      -l chown-ignore                                                                -d "Have all chowns fail silently"
complete -f bindfs      -l chgrp-ignore                                                                -d "Have all chgrps fail silently"
complete -f bindfs      -l chmod-ignore                                                                -d "Have all chmods fail silently"
complete -f bindfs      -l chown-deny                                                                  -d "Have all chowns fail with 'permission denied'"
complete -f bindfs      -l chgrp-deny                                                                  -d "Have all chgrps fail with 'permission denied'"
complete -f bindfs      -l chmod-deny                                                                  -d "Have all chmods fail with 'permission denied'"
complete -f bindfs      -l chmod-allow-x                                                               -d "Allow changing file execute bits in any case"
complete -f bindfs      -l xattr-none                                                                  -d "Do not implement xattr operations"
complete -f bindfs      -l xattr-ro                                                                    -d "Read-only xattr operations"
complete -f bindfs      -l xattr-rw                                                                    -d "Read-write xattr operations"
complete -f bindfs      -l delete-deny                                                                 -d "Disallow deleting files"
complete -f bindfs      -l rename-deny                                                                 -d "Disallow renaming files"
complete -f bindfs      -l no-allow-other                                                              -d "Do not add -o allow_other to fuse options"
complete -f bindfs      -l realistic-permissions                                                       -d "Hide permission bits for actions mounter can't do"
complete -f bindfs      -l ctime-from-mtime                                                            -d "Read file properties' change time from file content modification time"
complete -f bindfs      -l enable-lock-forwarding                                                      -d "Forward locks to the underlying FS"
complete -f bindfs      -l enable-ioctl                                                                -d "Forward ioctl() calls (as the mounter)"
complete -f bindfs      -l hide-hard-links                                                             -d "Always report a hard link count of 1"
complete -f bindfs      -l resolve-symlinks                                                            -d "Resolve symbolic links"
complete -f bindfs      -l block-devices-as-files                                                      -d "Show block devices as regular files"
complete -f bindfs      -l multithreaded                                                               -d "Enable multithreaded mode"