complete -f crossdev -s L  -l llvm               -d "Use LLVM/Clang as a cross compiler"
complete -f crossdev -s f  -l force              -d "I don't need a seat belt!"
complete -f crossdev -s S  -l stable             -d "Use latest stable versions as default"
complete -f crossdev -s A  -l abis            -r -d "Specify ABIs to build, first one is the default"
complete -f crossdev -s C  -l clean           -r -d "Uninstall specified target"
complete -f crossdev -s P  -l portage         -r -d "Options to pass to emerge"
complete -f crossdev -l b  -l binutils        -r -d "Specify version of binutils to use"
complete -f crossdev -l g  -l gcc             -r -d "Specify version of gcc to use"
complete -f crossdev -l k  -l kernel          -r -d "Specify version of kernel headers to use"
complete -f crossdev -l l  -l libc            -r -d "Specify version of libc to use"
complete -f crossdev -l r  -l crt             -r -d "Specify version of compiler-rt to use"
complete -f crossdev -l u  -l libunwind       -r -d "Specify version of libunwind to use"
complete -f crossdev -l a  -l libcxxabi       -r -d "Specify version of libcxxabi to use"
complete -f crossdev -l p  -l libcxx          -r -d "Specify version of libcxx to use"
complete -f crossdev -l c  -l ccw             -r -d "Specify version of clang-crossdev-wrapper to use"
complete -f crossdev -o s0 -l stage0             -d "Build just binutils"
complete -f crossdev -o s1 -l stage1             -d "Also build a bare C compiler (no C library/C++/shared GCC libs/C++ exceptions/etc...)"
complete -f crossdev -o s2 -l stage2             -d "Also build kernel headers"
complete -f crossdev -o s3 -l stage3             -d "Also build the C library"
complete -f crossdev -o s4 -l stage4             -d "Also build a full compiler [default](shared libs GCC/various lang frontends/etc...)"
complete -f crossdev -o oS -l overlays        -r -d "Space delimited list of overlays to search"
complete -F crossdev -o oO -l ov-output       -r -d "Parent directory of overlay to write crossdev package links"
complete -F crossdev -o ob -l ov-binutils     -r -d "Overlay for binutils ebuilds [default: search]"
complete -F crossdev -o od -l ov-gdb          -r -d "Overlay for gdb ebuilds [default: search]"
complete -F crossdev -o og -l ov-gcc          -r -d "Overlay for gcc ebuilds [default: search]"
complete -F crossdev -o ok -l ov-kernel       -r -d "Overlay for kernel ebuilds [default: search]"
complete -F crossdev -o ol -l ov-libc         -r -d "Overlay for C library ebuilds [default: search]"
complete -F crossdev -o ox -l ov-extra        -r -d "Overlay for extra packages [default: search]"
complete -F crossdev -o or -l ov-crt          -r -d "Overlay for compiler-rt ebuilds [default: search]"
complete -F crossdev -o oc -l ov-ccw          -r -d "Overlay for clang-crossdev-wrapper ebuilds [default: search]"
complete -f crossdev       -l host-abi        -r -d "Specify the ABI of the compiler itself"
complete -f crossdev       -l env             -r -d "Specify env settings for all packages (see below)"
complete -f crossdev       -l benv            -r -d "Specify env settings for binutils"
complete -f crossdev       -l denv            -r -d "Specify env settings for gdb"
complete -f crossdev       -l genv            -r -d "Specify env settings for gcc"
complete -f crossdev       -l kenv            -r -d "Specify env settings for kernel"
complete -f crossdev       -l lenv            -r -d "Specify env settings for libc"
complete -f crossdev       -l bcat            -r -d "Use binutils package from category"
complete -f crossdev       -l dcat            -r -d "Use gdb package from category"
complete -f crossdev       -l gcat            -r -d "Use gcc package from category"
complete -f crossdev       -l kcat            -r -d "Use kernel package from category"
complete -f crossdev       -l lcat            -r -d "Use libc package from category"
complete -f crossdev       -l bpkg            -r -d "Use binutils package with given name"
complete -f crossdev       -l dpkg            -r -d "Use gdb package with given name"
complete -f crossdev       -l gpkg            -r -d "Use gcc package with given name"
complete -f crossdev       -l kpkg            -r -d "Use kernel package with given name"
complete -f crossdev       -l lpkg            -r -d "Use libc package with given name"
complete -f crossdev       -l renv            -r -d "Specify env settings for compiler-rt"
complete -f crossdev       -l uenv            -r -d "Specify env settings for libunwind"
complete -f crossdev       -l aenv            -r -d "Specify env settings for libcxxabi"
complete -f crossdev       -l penv            -r -d "Specify env settings for libcxx"
complete -f crossdev       -l cenv            -r -d "Specify env settings for clang-crossdev-wrapper"
complete -f crossdev       -l rcat            -r -d "Use compiler-rt package from category"
complete -f crossdev       -l ucat            -r -d "Use libunwind package from category"
complete -f crossdev       -l acat            -r -d "Use libcxxabi package from category"
complete -f crossdev       -l pcat            -r -d "Use libcxx package from category"
complete -f crossdev       -l ccat            -r -d "Use clang-crossdev-wrapper package from category"
complete -f crossdev       -l rpkg            -r -d "Use compiler-rt package with given name"
complete -f crossdev       -l upkg            -r -d "Use libunwind package with given name"
complete -f crossdev       -l apkg            -r -d "Use libcxxabi package with given name"
complete -f crossdev       -l ppkg            -r -d "Use libcxx package with given name"
complete -f crossdev       -l ex-pkg          -r -d "Build extra packages (may be used multiple times)"
complete -f crossdev       -l cpkg            -r -d "Use clang-crossdev-wrapper package with given name"
complete -f crossdev       -l with-headers       -d "Build C library headers before C compiler"
complete -f crossdev       -l without-headers    -d "Build C library headers after C compiler"
complete -f crossdev       -l show-fail-log      -d "If the build fails, dump the failing log"
complete -f crossdev       -l show-target-cfg    -d "Display target settings that crossdev will use"
complete -f crossdev       -l init-target        -d "Setup config/overlay/etc... files only"
complete -f crossdev       -l ex-only            -d "Skip the stage steps above"
complete -f crossdev       -l ex-gcc             -d "Build extra gcc targets (ada/d/fortran/etc...)"
complete -f crossdev       -l ex-gdb             -d "Build a cross gdb"