complete -F dtc -s d -l out-dependency -r -d 'Output dependency file'
complete -F dtc -s o -l out            -r -d 'Output file'
complete -F dtc -s i -l include        -r -d 'Add a path to search for include files'
complete -f dtc -s a -l align          -r -d 'Make the blob align to the <bytes> (extra space)'
complete -f dtc -s b -l boot-cpu       -r -d 'Set the physical boot cpu'
complete -f dtc -s E -l error          -r -d 'Enable/disable errors (prefix with "no-")'
complete -f dtc -s p -l pad            -r -d 'Add padding to the blob of <bytes> long (extra space)'
complete -f dtc -s R -l reserve        -r -d 'Make space for <number> reserve map entries (for dtb and asm output)'
complete -f dtc -s S -l space          -r -d 'Make the blob at least <bytes> long (extra space)'
complete -f dtc -s V -l out-version    -r -d 'Blob version to produce, defaults to 17 (for dtb and asm output)'
complete -f dtc -s W -l warning        -r -d 'Enable warnings'
complete -f dtc -s A -l auto-alias        -d 'Enable auto-alias of labels'
complete -f dtc -s f -l force             -d 'Try to produce output even if the input tree has errors'
complete -f dtc -s h -l help              -d 'Print help and exit'
complete -f dtc -s L -l local-fixups      -d 'Possibly generates a __local_fixups__ and a __fixups__ node at the root node'
complete -f dtc -s q -l quiet             -d 'suppress warnings/errors(-qq)/all(-qqq)'
complete -f dtc -s s -l sort              -d 'Sort nodes and properties before outputting (useful for comparing trees)'
complete -f dtc -s T -l annotate          -d 'Annotate output .dts with input source file and line'
complete -f dtc -s v -l version           -d 'Print version and exit'
complete -f dtc -s @ -l symbols           -d 'Enable generation of symbols'
complete -f dtc      -l no-error       -r -d 'Enable errors'
complete -f dtc      -l no-warning     -r -d 'Disable warnings'

complete -x dtc -s I -l in-format -a dts -d 'device tree source text'
complete -x dtc -s I -l in-format -a dtb -d 'device tree blob'
complete -x dtc -s I -l in-format -a fs  -d '/proc/device-tree style directory'
complete -f dtc -s I -l in-format        -d 'Set Input formats'

complete -x dtc -s O -l out-format -a dts  -d 'device tree source text'
complete -x dtc -s O -l out-format -a dtb  -d 'device tree blob'
complete -x dtc -s O -l out-format -a yaml -d 'device tree encoded as YAML'
complete -x dtc -s O -l out-format -a asm  -d 'assembler source'
complete -f dtc -s O -l out-format         -d 'set Output formats'

complete -f dtc -s H -l phandle -a legacy -d '"linux,phandle" properties only'
complete -f dtc -s H -l phandle -a epapr  -d '"phandle" properties only'
complete -f dtc -s H -l phandle -a both   -d 'Both "linux,phandle" and "phandle" properties'
complete -f dtc -s H -l phandle           -d 'Set phandle formats'
