complete -c fallocate -s l -l length         -d "范围操作的长度(字节数)"
complete -c fallocate -s o -l offset         -d "范围操作的偏移量(字节数)"
complete -c fallocate -s c -l collapse-range -d "移除文件中的某个范围"
complete -c fallocate -s d -l dig-holes      -d "检测零并替换为空洞"
complete -c fallocate -s i -l insert-range   -d "insert a hole at range, shifting existing data"
complete -c fallocate -s n -l keep-size      -d "保持文件的显示大小"
complete -c fallocate -s p -l punch-hole     -d "将某个范围替换为空洞(连带打开 -n)"
complete -c fallocate -s z -l zero-range     -d "清零并保证分配某个范围"
complete -c fallocate -s x -l posix          -d "使用 posix_fallocate 而非 fallocate"
complete -c fallocate -s v -l verbose        -d "详尽模式"
complete -c fallocate -s h -l help           -d "显示此帮助"
complete -c fallocate -s V -l version        -d "显示版本"
