complete -F makechrootpkg -s d -r -d "Bind directory into build chroot as read-write"
complete -F makechrootpkg -s D -r -d "Bind directory into build chroot as read-only"
complete -F makechrootpkg -s I -r -d "Install a package into the working copy of the chroot"
complete -F makechrootpkg -s r -r -d "The chroot dir to use"
complete -F makechrootpkg -s t -r -d "Mount a tmpfs at directory"
complete -f makechrootpkg -s l -r -d "The directory to use as the working copy of the chroot"
complete -f makechrootpkg -s c    -d "Clean the chroot before building"
complete -f makechrootpkg -s C    -d "Run checkpkg on the package"
complete -f makechrootpkg -s h    -d "Show help"
complete -f makechrootpkg -s n    -d "Run namcap on the package"
complete -f makechrootpkg -s T    -d "Build in a temporary directory"
complete -f makechrootpkg -s u    -d "Update the working copy of the chroot before building"
complete -f makechrootpkg -s U    -d "Run makepkg as a specified user"

complete -x makechrootpkg -s x -a never   -d "Never inspect chroot after build"
complete -x makechrootpkg -s x -a always  -d "Always inspect chroot after build"
complete -x makechrootpkg -s x -a failure -d "Inspect chroot if build failed"
complete -f makechrootpkg -s x            -d "Inspect chroot after build (never, always, failure)"
