complete -F pycargoebuild
complete -f pycargoebuild -s c -l crate-tarball                               -d "Pack fetched crates into a tarball"
complete -F pycargoebuild -s d -l distdir                                  -r -d "Directory to store downloaded crates in"
complete -f pycargoebuild -s e -l features                                    -d "Add USE flags for Cargo features"
complete -F pycargoebuild -s o -l output                                   -r -d "Ebuild file to write"
complete -x pycargoebuild -s F -l fetcher                -a "auto aria2 wget" -d "Fetcher to use"
complete -f pycargoebuild -s f -l force                                       -d "Force overwriting the output file"
complete -f pycargoebuild -s h -l help                                        -d "show help message and exit"
complete -f pycargoebuild -s i -l input -l inplace                            -d "Update the CRATES and LICENSE variables in the specified ebuild instead of creating one from scratch"
complete -f pycargoebuild -s L -l no-license                                  -d "Do not include LICENSEs"
complete -f pycargoebuild -s l -l license-mapping                             -d "LICENSE_MAPPING Path to license-mapping.conf file"
complete -f pycargoebuild -s M -l no-manifest                                 -d "Do not call pkgdev manifest"
complete -x pycargoebuild      -l crate-tarball-prefix                        -d "Prefix prepended for all paths in the crate tarball"
complete -f pycargoebuild      -l no-write-crate-tarball                      -d "Do not create the crate tarball, just write the ebuild assuming it exists"
complete -f pycargoebuild      -l no-config                                   -d "Inhibit loading configuration files"
complete -F pycargoebuild      -l crate-tarball-path                       -r -d "Path to write crate tarball to"