complete -f wpm -s c -l clean                                      -d "cleans up downloaded apps"
complete -f wpm -s v -l version                                    -d "Shows version info"
complete -f wpm -s s -l search     | search                        -d "Searches all repos for a package"
complete -f wpm -s l -l listrepos  | listrepos                     -d "Lists all added fdroid repos"
complete -f wpm -s m -l listapps   | listapps                      -d "Lists all installed apps"
complete -f wpm -s a -l addrepo    | addrepo    -a (repo repo_url) -d "Adds a new fdroid repo"
complete -f wpm -s r -l removerepo | removerepo -a          (repo) -d "Removes a repo"
complete -f wpm -s u -l updaterepo | updaterepo -a (repo repo_url) -d "Updates a new fdroid repo"
complete -f wpm -s i -l install    | install    -a      (app_name) -d "Searches for & installs an app"
complete -f wpm -s n -l remove     | remove     -a      (app_name) -d "uninstalls an app"
complete -f wpm -s p -l apkinstall | apkinstall -a  (apk_location) -d "installs an apk"
